version: '3'
services:
  mysql-db:
    container_name: mysql-db
    env_file:
      - .env
    image: "mysql/mysql-server:5.7"
    ports:
      - "3307:3306"
    networks:
      springboot-mysql-network:
    environment:
      - MYSQL_ONETIME_PASSWORD=true


  springboot-mysql-app:
    container_name: springboot-mysql-app
    image: springboot-mysql-app:latest
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /
    ports:
      - "8088:8085"
    depends_on:
      - mysql-db
    networks:
      springboot-mysql-network:
    environment:
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db/${MYSQL_DB}?useSSL=false&allowPublicKeyRetrieval=true
    command: mvn clean spring-boot:run

networks:
  springboot-mysql-network: